# See https://cloud.google.com/cloud-build/docs/build-config
options:
  substitution_option: ALLOW_LOOSE
  machineType: E2_HIGHCPU_32
steps:
- name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20240718-5ef92b5c36
  entrypoint: make
  env:
  - REGISTRY=us-central1-docker.pkg.dev/k8s-staging-images/cloud-provider-kind
  - IMAGE_NAME=cloud-controller-manager
  args: ['release']
