apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeroapp
spec:
  selector:
    matchLabels:
      app: zeroapp
  replicas: 2
  template:
    metadata:
      labels:
        app: zeroapp
    spec:
      terminationGracePeriodSeconds: 30
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - zeroapp
            topologyKey: kubernetes.io/hostname
      containers:
      - name: zeroapp
        image: registry.k8s.io/e2e-test-images/agnhost:2.39
        args:
          - netexec
          - --http-port=80
          - --delay-shutdown=30
        ports:
          - name: httpd
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: zeroapp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: zeroapp
  ports:
    - name: httpd
      port: 80
      targetPort: 80