name: e2e

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  GO_VERSION: "1.20.1"
  K8S_VERSION: "v1.26.0"
  KIND_VERSION: "v0.17.0"
  KIND_CLUSTER_NAME: "kind-cloud"

jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    timeout-minutes: 100
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Enable ipv4 and ipv6 forwarding
      run: |
        sudo sysctl -w net.ipv6.conf.all.forwarding=1
        sudo sysctl -w net.ipv4.ip_forward=1

    - name: Install test dependencies
      run: sudo apt-get -y install bats ncat

    - name: Run tests
      run: |
        make e2e

