name: e2e

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  GO_VERSION: "1.20.4"

jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    timeout-minutes: 100
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Enable ipv4 and ipv6 forwarding
      run: |
        sudo sysctl -w net.ipv6.conf.all.forwarding=1
        sudo sysctl -w net.ipv4.ip_forward=1

    - name: Setup BATS
      uses: mig4/setup-bats@v1
      with:
        bats-version: 1.2.1

    - name: Run tests
      run: |
        make e2e

